apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-jumpstarter-script
spec:
  params:
    - name: scriptFile
      type: string
    - name: imageFile
      type: string
  steps:
    - image: 'quay.io/mangelajo/ubi9-jumpstarter:0.3.2-2'
      name: info
      resources: {}
      script: |
        #!/usr/bin/env sh

        set -x

        jumpstarter list-devices

        ls $(workspaces.images.path)
        ls $(workspaces.scripts.path)
        ls $(workspaces.artifacts.path)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /dev
          name: dynamic-devices
    - image: 'quay.io/mangelajo/ubi9-jumpstarter:0.3.2-2'
      name: prepare-image-and-run
      resources: {}
      script: >
        #!/usr/bin/env sh

        set -x

        cp $(workspaces.images.path)/$(params.imageFile) .

        xz -d -T0 -v $(params.imageFile)


        # inject an authorized key

        mkdir -p mount/root/.ssh

        [[ -f ~/.ssh/id_rsa ]] ||  ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q
        -N ""


        mkdir -p mount

        LIBGUESTFS_BACKEND=direct guestmount -a rhel-guest-image.raw \
         -m /dev/sda3:/ -m /dev/sda2:/boot -o allow_other --rw mount

        trap "guestunmount ${PWD}/mount" ERR SIGINT

        cp ~/.ssh/id_rsa.pub mount/root/.ssh/authorized_keys

        chmod 700 mount/root/.ssh

        chmod 600 mount/root/.ssh/authorized_keys


        # unmount the image

        guestunmount mount

        trap - ERR SIGINT

        dnf install -y rsync

        # copy the scripts to the working directory and run

        cp -rfv $(workspaces.scripts.path)/* .

        jumpstarter run-script $(params.scriptFile)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /dev
          name: dynamic-devices
  volumes:
    - hostPath:
        path: /dev
      name: dynamic-devices
  workspaces:
    - description: The script sources to be ran with jumpstarter
      name: scripts
    - description: The images to be used by the jumpstarter script
      name: images
      optional: true
    - description: The output directory for artifacts
      name: artifacts
      optional: true
