apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-rhel-image
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvms-vg1
